### ISSUE TITLE
Adding detection for Mac keyboard Alt+Space

### ISSUE THREAD

**Issue by jareware** [harley84/ZeroLengthRadar#1]
Thanks for a useful plugin! It would look like it's rather easy to add [new forbidden chars](https://github.com/harley84/ZeroLengthRadar/blob/master/src/main/java/com/ultrahob/zerolength/InvisibleCharacterInspection.java#L24-27). Do you think this plugin could also report on oddities like the [Mac Alt+Space](http://superuser.com/questions/78245/how-to-disable-the-option-space-key-combination-for-non-breaking-spaces) one?

Just spent 15 minutes thinking I was going crazy...

**Comment by harley84** [comment]
Thanks! I'm not familiar with Macs. What UTF character does Alt+Space create?

**Comment by jareware** [comment]
[This one](http://www.fileformat.info/info/unicode/char/00a0/index.htm) if I'm not mistaken.
