### ISSUE TITLE
New zero length character (U+200E)

### ISSUE THREAD

**Issue by asrob** [harley84/ZeroLengthRadar#3]
Hi!

I'm using this plugin with PhpStorm 9.0.1 and there are another invisible characters that I cannot see in editor. Here they are: http://www.fileformat.info/info/unicode/char/200e/index.htm and http://www.fileformat.info/info/unicode/char/200f/index.htm

Can you update your plugin so as to I can see and remove them via PhpStorm?

Thanks!

**Comment by vsch** [comment]
@asrob, I too needed this but could no longer wait. I also wanted to have quick fixes to remove the characters. Just knowing they are there is good but to remove them required writing a regex replace. I also got fed up of the huge repeated tooltips when there are many locations with invisible characters found in the element.

1. Added the characters you listed. 
2. Added quick fixes. Zero width are removed, NonBreak space is replaced by space not to affect layout.
3. Combined all problems into one per element for all found invisibles.
4. Added file level problem report with quick fixes for all found invisibles and one per invisible.

I posted a PR #4 but if you don't want to wait for the official version you can download the fixed plugin from <https://github.com/vsch/ZeroLengthRadar>  in the dist directory or directly from this link <https://github.com/vsch/ZeroLengthRadar/blob/master/dist/ZeroLengthRadar.0.92.jar?raw=true>

**Comment by harley84** [comment]
Should be fixed in 0.92.
The update will be published as soon as Jetbrains approve it.
